development:
  adapter: postgresql
  encoding: utf8
  database: beanstalk-test_development
  pool: 5
  username: postgres
  host: localhost
  template: template0

test:
  adapter: postgresql
  encoding: utf8
  database: beanstalk-test_test
  pool: 5
  username: postgres
  min_messages: WARNING
  host: localhost
  template: template0

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV[‘RDS_DB_NAME’] %>
  pool: 5
  username: <%= ENV[‘RDS_USERNAME’] %>
  password: <%= ENV[‘RDS_PASSWORD’] %>
  host: <%= ENV[‘RDS_HOSTNAME’] %>
  port: <%= ENV[‘RDS_PORT’] %>
  template: template0
